-- MySQL Script generated by MySQL Workbench
-- qua 30 abr 2025 08:45:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico` (
  `idhistorico` INT NOT NULL,
  PRIMARY KEY (`idhistorico`),
  UNIQUE INDEX `idhistorico_UNIQUE` (`idhistorico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `historico_idhistorico` INT NOT NULL,
  `historico_idhistorico1` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `historico_idhistorico`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE,
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  INDEX `fk_cliente_historico1_idx` (`historico_idhistorico1` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_historico1`
    FOREIGN KEY (`historico_idhistorico1`)
    REFERENCES `mydb`.`historico` (`idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebida` (
  `idbebida` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `volume` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idbebida`),
  UNIQUE INDEX `idbebida_UNIQUE` (`idbebida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combo` (
  `idcombo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `bebidas_idbebida` INT NOT NULL,
  `hamburgueres_idhamburguer` INT NOT NULL,
  `bebida_idbebida` INT NOT NULL,
  PRIMARY KEY (`idcombo`, `bebidas_idbebida`, `hamburgueres_idhamburguer`),
  UNIQUE INDEX `idcombo_UNIQUE` (`idcombo` ASC) VISIBLE,
  INDEX `fk_combo_bebida1_idx` (`bebida_idbebida` ASC) VISIBLE,
  CONSTRAINT `fk_combo_bebida1`
    FOREIGN KEY (`bebida_idbebida`)
    REFERENCES `mydb`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguer` (
  `idhamburguer` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `combo_idcombo` INT NOT NULL,
  `combo_bebidas_idbebida` INT NOT NULL,
  `combo_hamburgueres_idhamburguer` INT NOT NULL,
  PRIMARY KEY (`idhamburguer`),
  UNIQUE INDEX `idhamburguer_UNIQUE` (`idhamburguer` ASC) VISIBLE,
  INDEX `fk_hamburguer_combo1_idx` (`combo_idcombo` ASC, `combo_bebidas_idbebida` ASC, `combo_hamburgueres_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguer_combo1`
    FOREIGN KEY (`combo_idcombo` , `combo_bebidas_idbebida` , `combo_hamburgueres_idhamburguer`)
    REFERENCES `mydb`.`combo` (`idcombo` , `bebidas_idbebida` , `hamburgueres_idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adicional` (
  `idadicional` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(10,2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadicional`),
  UNIQUE INDEX `idadicional_UNIQUE` (`idadicional` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adicional_combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adicional_combo` (
  `adicional_idadicional` INT NOT NULL,
  `combo_idcombo` INT NOT NULL,
  `combo_bebidas_idbebida` INT NOT NULL,
  `combo_hamburgueres_idhamburguer` INT NOT NULL,
  INDEX `fk_combo_has_adicional_adicional1_idx` (`adicional_idadicional` ASC) VISIBLE,
  INDEX `fk_combo_has_adicional_combo1_idx` (`combo_idcombo` ASC, `combo_bebidas_idbebida` ASC, `combo_hamburgueres_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_combo_has_adicional_adicional1`
    FOREIGN KEY (`adicional_idadicional`)
    REFERENCES `mydb`.`adicional` (`idadicional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combo_has_adicional_combo1`
    FOREIGN KEY (`combo_idcombo` , `combo_bebidas_idbebida` , `combo_hamburgueres_idhamburguer`)
    REFERENCES `mydb`.`combo` (`idcombo` , `bebidas_idbebida` , `hamburgueres_idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL,
  `historico_idhistorico` INT NOT NULL,
  `historico_idhistorico1` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `historico_idhistorico`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC) VISIBLE,
  INDEX `fk_pedido_historico1_idx` (`historico_idhistorico1` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_historico1`
    FOREIGN KEY (`historico_idhistorico1`)
    REFERENCES `mydb`.`historico` (`idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cliente_idusuario` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `cliente_idusuario1` INT NOT NULL,
  `cliente_historico_idhistorico` INT NOT NULL,
  `pedido_idpedido1` INT NOT NULL,
  `pedido_historico_idhistorico` INT NOT NULL,
  PRIMARY KEY (`identrega`, `cliente_idusuario`, `pedido_idpedido`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE,
  INDEX `fk_entrega_cliente1_idx` (`cliente_idusuario1` ASC, `cliente_historico_idhistorico` ASC) VISIBLE,
  INDEX `fk_entrega_pedido1_idx` (`pedido_idpedido1` ASC, `pedido_historico_idhistorico` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_cliente1`
    FOREIGN KEY (`cliente_idusuario1` , `cliente_historico_idhistorico`)
    REFERENCES `mydb`.`cliente` (`idusuario` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_pedido1`
    FOREIGN KEY (`pedido_idpedido1` , `pedido_historico_idhistorico`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entregador` (
  `idfuncionario` INT NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` INT NOT NULL,
  `entrega_identrega` INT NOT NULL,
  `entrega_cliente_idusuario` INT NOT NULL,
  `entrega_pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`idfuncionario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_entregador_entrega1_idx` (`entrega_identrega` ASC, `entrega_cliente_idusuario` ASC, `entrega_pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_entregador_entrega1`
    FOREIGN KEY (`entrega_identrega` , `entrega_cliente_idusuario` , `entrega_pedido_idpedido`)
    REFERENCES `mydb`.`entrega` (`identrega` , `cliente_idusuario` , `pedido_idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idadministrador` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`),
  UNIQUE INDEX `idadministrador_UNIQUE` (`idadministrador` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_bebida` (
  `pedido_idpedido` INT NOT NULL,
  `pedido_historico_idhistorico` INT NOT NULL,
  `bebida_idbebida` INT NOT NULL,
  INDEX `fk_pedido_has_bebida_pedido1_idx` (`pedido_idpedido` ASC, `pedido_historico_idhistorico` ASC) VISIBLE,
  INDEX `fk_pedido_has_bebida_bebida1_idx` (`bebida_idbebida` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_bebida_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_historico_idhistorico`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_bebida_bebida1`
    FOREIGN KEY (`bebida_idbebida`)
    REFERENCES `mydb`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combo_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combo_pedido` (
  `pedido_idpedido` INT NOT NULL,
  `pedido_historico_idhistorico` INT NOT NULL,
  `combo_idcombo` INT NOT NULL,
  `combo_bebidas_idbebida` INT NOT NULL,
  `combo_hamburgueres_idhamburguer` INT NOT NULL,
  INDEX `fk_combo_has_pedido_pedido1_idx` (`pedido_idpedido` ASC, `pedido_historico_idhistorico` ASC) VISIBLE,
  INDEX `fk_combo_has_pedido_combo1_idx` (`combo_idcombo` ASC, `combo_bebidas_idbebida` ASC, `combo_hamburgueres_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_combo_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_historico_idhistorico`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combo_has_pedido_combo1`
    FOREIGN KEY (`combo_idcombo` , `combo_bebidas_idbebida` , `combo_hamburgueres_idhamburguer`)
    REFERENCES `mydb`.`combo` (`idcombo` , `bebidas_idbebida` , `hamburgueres_idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguer_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguer_pedido` (
  `pedido_idpedido` INT NOT NULL,
  `pedido_historico_idhistorico` INT NOT NULL,
  `combo_idcombo` INT NOT NULL,
  `combo_bebidas_idbebida` INT NOT NULL,
  `combo_hamburgueres_idhamburguer` INT NOT NULL,
  `hamburguer_idhamburguer` INT NOT NULL,
  INDEX `fk_hamburguer_has_pedido_pedido1_idx` (`pedido_idpedido` ASC, `pedido_historico_idhistorico` ASC) VISIBLE,
  INDEX `fk_hamburguer_has_pedido_combo1_idx` (`combo_idcombo` ASC, `combo_bebidas_idbebida` ASC, `combo_hamburgueres_idhamburguer` ASC) VISIBLE,
  INDEX `fk_hamburguer_has_pedido_hamburguer1_idx` (`hamburguer_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguer_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_historico_idhistorico`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hamburguer_has_pedido_combo1`
    FOREIGN KEY (`combo_idcombo` , `combo_bebidas_idbebida` , `combo_hamburgueres_idhamburguer`)
    REFERENCES `mydb`.`combo` (`idcombo` , `bebidas_idbebida` , `hamburgueres_idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hamburguer_has_pedido_hamburguer1`
    FOREIGN KEY (`hamburguer_idhamburguer`)
    REFERENCES `mydb`.`hamburguer` (`idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_combo` (
  `cliente_idusuario` INT NOT NULL,
  `cliente_historico_idhistorico` INT NOT NULL,
  `combo_idcombo` INT NOT NULL,
  `combo_bebidas_idbebida` INT NOT NULL,
  `combo_hamburgueres_idhamburguer` INT NOT NULL,
  PRIMARY KEY (`cliente_idusuario`, `cliente_historico_idhistorico`, `combo_idcombo`, `combo_bebidas_idbebida`, `combo_hamburgueres_idhamburguer`),
  INDEX `fk_cliente_has_combo_combo1_idx` (`combo_idcombo` ASC, `combo_bebidas_idbebida` ASC, `combo_hamburgueres_idhamburguer` ASC) VISIBLE,
  INDEX `fk_cliente_has_combo_cliente1_idx` (`cliente_idusuario` ASC, `cliente_historico_idhistorico` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_combo_cliente1`
    FOREIGN KEY (`cliente_idusuario` , `cliente_historico_idhistorico`)
    REFERENCES `mydb`.`cliente` (`idusuario` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_combo_combo1`
    FOREIGN KEY (`combo_idcombo` , `combo_bebidas_idbebida` , `combo_hamburgueres_idhamburguer`)
    REFERENCES `mydb`.`combo` (`idcombo` , `bebidas_idbebida` , `hamburgueres_idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`montagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montagem` (
  `idmontagem` INT NOT NULL,
  `hamburguer` INT NULL,
  `presunto` INT NULL,
  `mussarela` INT NULL,
  `alface` INT NULL,
  `tomate` INT NULL,
  `salsicha` INT NULL,
  `ovo` INT NULL,
  `bacon` INT NULL,
  `milho` INT NULL,
  `batata` INT NULL,
  `pao` INT NOT NULL,
  `frango` INT NULL,
  `quantidade` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `pedido_historico_idhistorico` INT NOT NULL,
  PRIMARY KEY (`idmontagem`),
  UNIQUE INDEX `idmontagem_UNIQUE` (`idmontagem` ASC) VISIBLE,
  INDEX `fk_montagem_pedido1_idx` (`pedido_idpedido` ASC, `pedido_historico_idhistorico` ASC) VISIBLE,
  CONSTRAINT `fk_montagem_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_historico_idhistorico`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `historico_idhistorico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
