-- MySQL Script generated by MySQL Workbench
-- seg 16 jun 2025 14:19:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hamburguer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguer` (
  `idhamburguer` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhamburguer`),
  UNIQUE INDEX `idhamburguer_UNIQUE` (`idhamburguer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebida` (
  `idbebida` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `volume` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idbebida`),
  UNIQUE INDEX `idbebida_UNIQUE` (`idbebida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adicional` (
  `idadicional` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(10,2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadicional`),
  UNIQUE INDEX `idadicional_UNIQUE` (`idadicional` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combo` (
  `idcombo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `bebida_idbebida` INT NOT NULL,
  `adicional_idadicional` INT NOT NULL,
  `hamburguer_idhamburguer` INT NOT NULL,
  PRIMARY KEY (`idcombo`),
  UNIQUE INDEX `idcombo_UNIQUE` (`idcombo` ASC) VISIBLE,
  INDEX `fk_combo_bebida1_idx` (`bebida_idbebida` ASC) VISIBLE,
  INDEX `fk_combo_adicional1_idx` (`adicional_idadicional` ASC) VISIBLE,
  INDEX `fk_combo_hamburguer1_idx` (`hamburguer_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_combo_bebida1`
    FOREIGN KEY (`bebida_idbebida`)
    REFERENCES `mydb`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combo_adicional1`
    FOREIGN KEY (`adicional_idadicional`)
    REFERENCES `mydb`.`adicional` (`idadicional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combo_hamburguer1`
    FOREIGN KEY (`hamburguer_idhamburguer`)
    REFERENCES `mydb`.`hamburguer` (`idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entregador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entregador` (
  `identregador` INT NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`identregador`),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`identregador` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idadministrador_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `entregador_identregador` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  UNIQUE INDEX `identrega_UNIQUE` (`identrega` ASC) VISIBLE,
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE,
  INDEX `fk_entrega_entregador1_idx` (`entregador_identregador` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_entrega_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_entregador1`
    FOREIGN KEY (`entregador_identregador`)
    REFERENCES `mydb`.`entregador` (`identregador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho` (
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idcarrinho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`montagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`montagem` (
  `idmontagem` INT NOT NULL,
  `hamburguer` INT NULL,
  `presunto` INT NULL,
  `mussarela` INT NULL,
  `alface` INT NULL,
  `tomate` INT NULL,
  `salsicha` INT NULL,
  `ovo` INT NULL,
  `bacon` INT NULL,
  `milho` INT NULL,
  `batata` INT NULL,
  `pao` INT NOT NULL,
  `frango` INT NULL,
  `quantidade` INT NOT NULL,
  `carrinho_idcarrinho` INT NOT NULL,
  PRIMARY KEY (`idmontagem`),
  UNIQUE INDEX `idmontagem_UNIQUE` (`idmontagem` ASC) VISIBLE,
  INDEX `fk_montagem_pedido1_idx` (`carrinho_idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_montagem_pedido1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho_bebida` (
  `carrinho_idcarrinho` INT NOT NULL,
  `bebida_idbebida` INT NOT NULL,
  INDEX `fk_pedido_has_bebida_bebida1_idx` (`bebida_idbebida` ASC) VISIBLE,
  INDEX `fk_pedido_has_bebida_pedido1_idx` (`carrinho_idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_bebida_pedido1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_bebida_bebida1`
    FOREIGN KEY (`bebida_idbebida`)
    REFERENCES `mydb`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguer_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguer_carrinho` (
  `hamburguer_idhamburguer` INT NOT NULL,
  `carrinho_idcarrinho` INT NOT NULL,
  INDEX `fk_hamburguer_has_pedido_pedido1_idx` (`carrinho_idcarrinho` ASC) VISIBLE,
  INDEX `fk_hamburguer_has_pedido_hamburguer1_idx` (`hamburguer_idhamburguer` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguer_has_pedido_hamburguer1`
    FOREIGN KEY (`hamburguer_idhamburguer`)
    REFERENCES `mydb`.`hamburguer` (`idhamburguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hamburguer_has_pedido_pedido1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
